version: '3'

services:
  db:
    container_name: db.postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    restart: always
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn fatihkocnet.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./fatihkocnet:/fatihkocnet
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "8000:8000"

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./fatihkocnet:/fatihkocnet
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
